<a href="https://colab.research.google.com/github/SHREYASHSHAURYA/ML-6th-Sem-Lab/blob/main/iris_datset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
from sklearn.datasets import load_iris

# 1. Load the Iris dataset
iris = load_iris()
df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df_iris['species'] = iris.target_names[iris.target]

print("1. Iris Dataset Loaded:")
display(df_iris.head())

1. Iris Dataset Loaded:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [7]:
# 2. Display basic information about the DataFrame
print("\n2. DataFrame Info:")
df_iris.info()

2. DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [8]:
# 3. Display descriptive statistics
print("\n3. Descriptive Statistics:")
display(df_iris.describe())

3. Descriptive Statistics:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [9]:
# 4. Check unique values in the 'species' column
print("\n4. Unique Species:")
display(df_iris['species'].unique())

4. Unique Species:

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [10]:
# 5. Group by 'species' and calculate the mean of numerical features
print("\n5. Mean of features grouped by Species:")
display(df_iris.groupby('species').mean())

5. Mean of features grouped by Species:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
setosa,5.006,3.428,1.462,0.246
versicolor,5.936,2.770,4.260,1.326
virginica,6.588,2.974,5.552,2.026

In [11]:
# 6. Filter data for a specific species (e.g., 'setosa')
print("\n6. Filtered data for 'setosa' species:")
df_setosa = df_iris[df_iris['species'] == 'setosa']
display(df_setosa.head())

6. Filtered data for 'setosa' species:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [12]:
# 7. Add a new calculated column: 'sepal_area'
df_iris['sepal_area'] = df_iris['sepal length (cm)'] * df_iris['sepal width (cm)']
print("\n7. DataFrame with 'sepal_area' column:")
display(df_iris.head())

7. DataFrame with 'sepal_area' column:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,sepal_area
0,5.1,3.5,1.4,0.2,setosa,17.85
1,4.9,3.0,1.4,0.2,setosa,14.70
2,4.7,3.2,1.3,0.2,setosa,15.04
3,4.6,3.1,1.5,0.2,setosa,14.26
4,5.0,3.6,1.4,0.2,setosa,18.00

In [13]:
# 8. Sort the DataFrame by 'sepal_area' in descending order
print("\n8. DataFrame sorted by 'sepal_area' (top 5 rows):")
df_sorted = df_iris.sort_values(by='sepal_area', ascending=False)
display(df_sorted.head())

8. DataFrame sorted by 'sepal_area' (top 5 rows):

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,sepal_area
131,7.9,3.8,6.4,2.0,virginica,30.02
117,7.7,3.8,6.7,2.2,virginica,29.26
109,7.2,3.6,6.1,2.5,virginica,25.92
15,5.7,4.4,1.5,0.4,setosa,25.08
14,5.8,4.0,1.2,0.2,setosa,23.20

In [14]:
# 9. Export the modified DataFrame to a new CSV file
output_filename_iris = 'iris_modified_data.csv'
df_iris.to_csv(output_filename_iris, index=False)
print(f"\n9. Modified Iris DataFrame exported to '{output_filename_iris}'")

9. Modified Iris DataFrame exported to 'iris_modified_data.csv'

In [15]:
# 10. Import the exported CSV back into a new DataFrame
df_reimported_iris = pd.read_csv(output_filename_iris)
print(f"\n10. Modified Iris DataFrame re-imported from '{output_filename_iris}':")
display(df_reimported_iris.head())

10. Modified Iris DataFrame re-imported from 'iris_modified_data.csv':

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,sepal_area
0,5.1,3.5,1.4,0.2,setosa,17.85
1,4.9,3.0,1.4,0.2,setosa,14.70
2,4.7,3.2,1.3,0.2,setosa,15.04
3,4.6,3.1,1.5,0.2,setosa,14.26
4,5.0,3.6,1.4,0.2,setosa,18.00